### ISSUE TITLE
Can't load font in godot 4.0

### ISSUE THREAD

**Issue by Shadowblitz16** [imjp94/UIDesignTool#14]
![image](https://github.com/imjp94/UIDesignTool/assets/2453707/cd2c6b0c-d872-4af1-b16f-9bfb2bfb2b6c)

**Comment by imjp94** [comment]
You have to create sub directory for each font, the project structure should look like this in your case:
- fonts
  - body
    - body.ttf

Then, select `fonts` directory when importing fonts, see [Import TrueType Font(.ttf)](https://github.com/imjp94/UIDesignTool#import-truetype-fontttf)

**Comment by Shadowblitz16** [comment]
ok ty
