### ISSUE TITLE
Toolbar's visibility only on editables nodes.

### ISSUE THREAD

**Issue by stebulba** [imjp94/UIDesignTool#4]
Toolbar is now visible on all GUI nodes. That can be confusing for the users and that can make some conflicts and errors.
On plugin.gd I replaced this function to make sure to active visibility of the toolbar only on effective text-label nodes with a list :
```
func _on_selection_changed():
	var selections = editor_selection.get_selected_nodes()
	var is_visible = false
	var focused_objects
	if selections.size() == 1:
		var selection = selections[0]
		if selection is Control:
			focused_objects = [selection]
			is_visible = true
	elif selections.size() > 1:
		var has_non_control = false
		for selection in selections:
			if not (selection is Control):
				has_non_control = true
				break
		if not has_non_control:
			is_visible = true
			focused_objects = selections
	else:
		focused_objects = []

	toolbar.visible = is_visible
	toolbar.focused_objects = focused_objects
	overlay_text_edit.focused_objects = focused_objects
```
by this one : 
```
var editables_nodes = ["Label","Button"] # list of editable nodes (make sure to add all editable node)

func _on_selection_changed():
	var focused_objects = []
	for selection in editor_selection.get_selected_nodes():
		if editables_nodes.find(selection.get_class()) != -1:
			focused_objects.append(selection)

	toolbar.visible = not focused_objects.empty()
	toolbar.focused_objects = focused_objects
	overlay_text_edit.focused_objects = focused_objects
```
I am thinking to upgrade the func load_fonts(dir) to be enable to get any fonts blend inside the directory you want to load.
Because, just as exemple when you download fonts on godot Assets the directory is not compatible with your tool.   
That will be for later. Anyway good job on that :)

**Comment by imjp94** [comment]
First of all, thank you for your interests in this project =)

1. Toolbar visibility on editable nodes:
    I agree that hiding toolbar from non-editable `Control` node can be foolproof to user not familiar with how Godot's `Control` node works, but I think suggested approach could lead to more problems:
    - Less flexible, filter selections with `.get_class()` will ignore custom `Control` nodes
    - Harder to maintain source code, using `is` keyword can check on custom `Control` nodes, but it would ended out in a long if/else chain, which could be error prone

    So, I am afraid that I cant accept your kind suggestion. Unless the plugin is unusable due to this, it is probably better to leave it this way for now until better solution has been figure out.

2. Improve `load_fonts(dir)`:
    Would you mind to elaborate more on the directory structure that you have?
    Do you mean directory like this:
    -  font_dir
        - font_file1.ttf
        - font_file2.ttf

PS: I appreciate the effort you took on analyzing my spaghetti code and making it better, but I suggest you to try adapting the workflow of [contribute to open source](https://github.com/firstcontributions/first-contributions) to get credited of what you contributed.

**Comment by stebulba** [comment]
1. VISIBILITY
What do you mind with "custom Control nodes" ? Like a node from a new addon ? 
If is that, it's not a issues, because the user can add is custom nodes in the array : editables_nodes = ["Label","Button"]
It's the avantage with a GDscript addons :-)
As I kwon, your addon work on those nodes ["Label","Button","CheckBox", "LineEdit", "RichTextLabel", "LinkButton", "ProgressBar", "MenuButton"]
If someone try to modify the color font of a TabContainer by your way, that will not work and he will report a bug. If the toolbar is not visible, the user will not lose time. 
Also initiate a instance toolbar variable on any Control nodes is in my mind not I good practice. Godot is small, we don't want grow the memory for nothing. Imagine a list of item. Each item have a HBoxContainer. 100 times undesirable toolbar variables for your HBoxContainer.

I have some alternative : (fist is same but avoid find(selection.get_class() if not a Control node.

```
var editables_nodes = ["Label","Button","CheckBox", "LineEdit", "RichTextLabel", "LinkButton", "ProgressBar", "MenuButton"]

func _on_selection_changed():
	var focused_objects = []
	for selection in editor_selection.get_selected_nodes():
		if selection is Control and editables_nodes.find(selection.get_class()) != -1:
			focused_objects.append(selection)

	toolbar.visible = not focused_objects.empty()
	toolbar.focused_objects = focused_objects
	overlay_text_edit.focused_objects = focused_objects
```

or make always invisible if a different Control node are selected for exemple : The best way for me.

```
var editables_nodes = ["Label","Button","CheckBox", "LineEdit", "RichTextLabel", "LinkButton", "ProgressBar", "MenuButton"]

func _on_selection_changed():
	var focused_objects = []
	for selection in editor_selection.get_selected_nodes():
		if selection is not Control:
			focused_objects = []
			break
		elif editables_nodes.find(selection.get_class()) != -1:
			focused_objects.append(selection)

	toolbar.visible = not focused_objects.empty()
	toolbar.focused_objects = focused_objects
	overlay_text_edit.focused_objects = focused_objects

OR 
		# only compatible node have to be selected
		if selection is Control && editables_nodes.find(selection.get_class()) != -1:
			focused_objects.append(selection)
		else:
			focused_objects = []
			break
```

I think the second is the best way. If all your node is selected in your scene, your forgot the toolbar.
Yes I will do a pull request if I modify your code. But for now I fell that is more a bug report you need a discussion.

2. FONTS :
I like the easier way to import font. For exemple to import those files in your directory is a puzzle : https://workupload.com/file/KZyaRzE
Your script should rearrange all the compatible files inside sub-repectory to by ready for importation with your script.
Because just to try your addon is difficult without a compatible fonts directory. On my mind you don't should need instruction or tutorial to import fonts. Godot suck for that. Your script should do the user job, and should doesn't matter the arrangement of the directory.

**Comment by imjp94** [comment]
1. "Custom `Control` node" as of new node `extends Control`

There's no memory overhead for the toolbar, there's always one and only toolbar that instanced when plugin initiated.

And I think this topic is more of a improvement than a bug.

2. For organising files, it is a big no no(at least for a UI design tool), nobody would expect this plugin to mess up their files.

Regarding difficulty in structuring directory, I will consider to improve it when there's more people find it the same. For now, current implementation should be good enough.

**Comment by stebulba** [comment]
> There's no memory overhead for the toolbar, there's always one and only toolbar that instanced when plugin initiated.

When you change font of a random node like a TextureRect with your toolbar, that color stay in memory until you close your Scene. That mind it's stay in memory. For any Control Node you click, they have a instance somewhere. 
That is maybe a bug.

When you have some options that they don't suppose to do and making confusion between a real option with a ghost option, It maybe calling a bug. 
definition "a mistake or problem in a computer program"
Godot's bug definition is very large too.

Anyways for my self I fixed that.
If I will work on the Fonts importation I will pull you my improvement.
Keep going :-)

**Comment by imjp94** [comment]
> When you change font of a random node like a TextureRect with your toolbar, that color stay in memory until you close your Scene.

I can confirm with this one, and submitted an issue(#5) myself.

Cheers =)
