### ISSUE TITLE
can not load font

### ISSUE THREAD

**Issue by sericaer** [imjp94/UIDesignTool#7]
你好，我用3.22的godot安装了这个插件，选择font目录加载对应的tff后，字体选项仍然是NULL。godot控制台报这个warning，能帮忙看一下吗？多谢！
Mono: Logfile is: C:\Users\fang\AppData\Roaming/Godot/mono/mono_logs/2020_10_09 22.48.08 (7124).txt
WARNING: call: UI Design Tool: Unable to locate usable .ttf files from D:/MyProject/GitHub/UIDesignToolDemo/resources/font, check README.md for proper directory/filename structure
     At: modules/gdscript/gdscript_functions.cpp:817

**Comment by imjp94** [comment]
你好，

> UI Design Tool: Unable to locate usable .ttf files from D:/MyProject/GitHub/UIDesignToolDemo/resources/font, check README.md for proper directory/filename structure
At: modules/gdscript/gdscript_functions.cpp:817

会出现以上错误是因为文件目录/命名格式不匹配，请参考[Import True Type Font](https://github.com/imjp94/UIDesignTool#import-truetype-fontttf)
如果还是不明白的话可以放上你当前的文件目录格式，我再教你怎么改

**Comment by sericaer** [comment]
多谢，问题已经解决
