### ISSUE TITLE
Can not set font in RichTextLabel 

### ISSUE THREAD

**Issue by sericaer** [imjp94/UIDesignTool#9]
在RichTextLabel 上设置字体，Godot提示这个错误

Change Rich Text Fonts
 res://addons/ui_design_tool/scenes/Toolbar.gd:412 - Invalid get index 'normal' (on base: 'Dictionary').

**Comment by imjp94** [comment]
Can confirmed this is a bug, thanks for reporting!

**Comment by imjp94** [comment]
@sericaer 
Here's a quick fix, copy the code snippet below to `addons\ui_design_tool\scenes\Toolbar.gd:411-414`
你可以先把以下代码copy/paste到`addons\ui_design_tool\scenes\Toolbar.gd:411-414`
```
var to = {}
to["regular"] = create_new_font_obj(font_family.regular.normal.data) if font_family.regular.get("normal") else null
to["bold"] = create_new_font_obj(font_family.bold.normal.data) if font_family.bold.get("normal") else null
to["regular_italic"] = create_new_font_obj(font_family.regular.italic.data)  if font_family.regular.get("italic") else null
to["bold_italic"] = create_new_font_obj(font_family.bold.italic.data) if font_family.bold.get("italic") else null
```

**Comment by imjp94** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix can't set font to RichTextLabel](https://trello.com/c/Q98zmRxU/102-fix-cant-set-font-to-richtextlabel)

**Comment by imjp94** [comment]
Fixed

**Comment by sericaer** [comment]
你好，RichTextLabel 上设置字体还是有一些问题。

现在RichTextLabel 上设置中文字体后，是可以正常显示中文的。但是保存重新打开对应的Scene后，编辑界面RichTextLabel 的字体属性还是“None”。

当前版本0.2.2

**Comment by imjp94** [comment]
你好@sericaer， 编辑界面无法确实的反映RichTextLabel的字体是正常的（正确的来说是我还没想到要怎么解决><）

原因是RichTextLabel可以设置多种字体（普通，粗体，斜体，粗斜体，等...），而字体之间未必是同一种。
所以直接套用针对单一字体的界面于RichTextLabel的结果就是，每一次设置字体都是直接覆盖。
![ezgif-3-6e481105a9c1](https://user-images.githubusercontent.com/11486079/105979028-2c700380-60ce-11eb-8201-39600132304e.gif)

我已经开多一个issue追踪这个缺陷: #10 
目前想得到的解决方案应该是要另做一个RichTextLabel的专属编辑界面。
